<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRaz3oF1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRaz3oF1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRaz3oF1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRaz3oF1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRaz3oF1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Raz3oF1',
    'container.build_id' => 'b501e958',
    'container.build_time' => 1562008342,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRaz3oF1');
